### ISSUE TITLE
Docker Action has a warning about a deprecated GHA config

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/repo2docker#1005]
Sounds like we need to update something in github actions:

![image](https://user-images.githubusercontent.com/1839645/105616538-b47fa180-5d8c-11eb-97a2-0caa48b59cab.png)

**Comment by betatim** [comment]
I think the message appears in the "build and push to docker hub" action https://github.com/jupyterhub/repo2docker/actions/runs/506449706. Can you confirm/deny that Chris?

If yes then I don't think it is related to the new PyPI action instead it is https://github.com/jupyterhub/repo2docker/blob/master/.github/workflows/docker.yml

**Comment by choldgraf** [comment]
Oops yep you’re right, I just quickly made this issue so that I didn’t forget noticing it! Will update the title
