### ISSUE TITLE
readthedocs CI has stopped

### ISSUE THREAD

**Issue by minrk** [jupyterhub/repo2docker#1015]
readthedocs isn't building PRs, despite the configuration being set in [advanced settings](https://readthedocs.org/dashboard/repo2docker/advanced/)

Maybe @choldgraf or @willingc has some insight on why this is or how to fix it?

I think we can remove the docs builds from circleci once we figure that out.

**Comment by choldgraf** [comment]
I betcha this is carryover from when we moved from `jupyter/` to `jupyterhub/`. I just made that switch on RTD, let's see if it starts building now.

**Comment by willingc** [comment]
This looks like it's building on RTD @minrk. Where are you seeing it not building?

**Comment by minrk** [comment]
> Where are you seeing it not building?

The CI status badge wasn't being added to PRs, though `latest` was still getting built. I see the badge now now for latest PR pushes, so I think you were right, @choldgraf. Thanks both!

I guess we need CI for our CI so we know when our builds aren't building...

![Yo-Dawg-Heard-You](https://user-images.githubusercontent.com/151929/108366099-42b63e80-71f8-11eb-9555-ca32d645e4ef.jpg)
