### ISSUE TITLE
Check if docker is running on the host

### ISSUE THREAD

**Issue by moldach** [jupyterhub/repo2docker#1021]
Checked the search results but couldn't find anything related to this.

Getting `docker` error despite it being installed.

I get an error when trying to run `repo2docker`

```
repo2docker) mtg@mtg-ThinkPad-P53:~/DOCKER-CONTAINERS/RUFUS$ jupyter-repo2docker https://github.com/jandrewrfarrell/RUFUS

Docker client initialization error: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied')).
Check if docker is running on the host.
```

However, `docker` works fine:

```
(repo2docker) mtg@mtg-ThinkPad-P53:~/DOCKER-CONTAINERS/RUFUS$ sudo docker run hello-world
[sudo] password for mtg: 

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

**Comment by manics** [comment]
You're running `repo2docker` as your standard user, but you're testing docker as root using `sudo`.

In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Hope you understand 😀.

**Comment by moldach** [comment]
Hi @manics I can respect that.

Question was does: `repo2docker` require that you run Docker in **Rootless Mode** - **Y/n**? So I've now cross-posted in the forum as well - https://discourse.jupyter.org/t/how-do-you-run-jupyter-repo2docker-without-rootless-mode/8033
