### ISSUE TITLE
Always unpack single zip files from Zenodo

### ISSUE THREAD

**Issue by akhmerov** [jupyterhub/repo2docker#1042]
### Proposed change

Uploading a .zip is the only way to represent folders on zenodo. It is also what zenodo does on github imports.

[Right now](https://github.com/jupyterhub/repo2docker/blob/master/repo2docker/contentproviders/zenodo.py#L71) repo2docker will only unpack the zip if DOI is marked as being software. I propose to unpack a single file unconditionally instead. The motivation is as follows:

- Some uploads containing both software and data (e.g. processing scripts) may classify themselves as datasets.
- If the user is facing a binder with a single zip file, their likely first step is to unzip said file.

The only downside I can think of is hitting disk space limits, however the workaround is trivial: the repository owner then needs to upload more than a single zip file. At the same time, currently the repository owner needs to choose any 2 out of the following 3 options:

- Having folders
- Having a functional binder
- Not labeling the repo as software

### Alternative options

Keep everything as it is...

### Who would use this feature?

Zenodo users

### How much effort will adding it take?

No effort (editing 2 lines), I'm about to open a PR.

### Who can do this work?

I can!

**Comment by betatim** [comment]
This sounds like a good idea.

I think one of the original thoughts when setting this up was to be able to tell the difference between a repo that contained one (or more?) ZIP files that weren't there because of the "when zenodo makes an entry from github it makes a zip" thing. But overall that was probably more speculation/hunch driven development than having seen a casein the wild.

**Comment by akhmerov** [comment]
The simplest scenario where the current behavior would break seems rather exotic.

1. The repo must contain a single zip and there should be some code that breaks if the binder contents are unpacked.
2. The user must have some code connecting to the binder. This code may not be inside the zip itself (because then the user wouldn't be able to execute the code from inside the zip).
3. So there must be some external tool like thebe, which programmatically starts the binder and then gets this extra unzipping code from somewhere else (?) and then everything breaks :boom: 

Seems sufficiently unlikely :upside_down_face:
