### ISSUE TITLE
external/reproductions.repos.yaml::10.5281/zenodo.3242074 is failing

### ISSUE THREAD

**Issue by manics** [jupyterhub/repo2docker#1070]
### Bug description
The `external/reproductions.repos.yaml::10.5281/zenodo.3242074` test is failing today on GitHub CI.

For example, https://github.com/jupyterhub/repo2docker/runs/3185970768
```
         except subprocess.CalledProcessError as e:
            msg = "Failed to clone repository from {repo}".format(repo=repo)
            if ref is not None:
                msg += " (ref {ref})".format(ref=ref)
            msg += "."
>           raise ContentProviderException(msg) from e
E           repo2docker.contentproviders.base.ContentProviderException: Failed to clone repository from 10.5281/zenodo.3242074.

/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/repo2docker/contentproviders/git.py:41: ContentProviderException
----------------------------- Captured stderr call -----------------------------
Picked Git content provider.
fatal: repository '10.5281/zenodo.3242074' does not exist
```

The DOI is resolving: https://doi.org/10.5281/zenodo.3242074

**Comment by betatim** [comment]
The weird thing is that on L99 of the test output it says `self = <repo2docker.contentproviders.git.Git object at 0x7fcfe664f250>` which makes me think it is using the Git repo content provider and not the Zenodo one :-/

**Comment by manics** [comment]
It's obviously been working for a while, but has broken again for a new reason https://github.com/jupyterhub/repo2docker/issues/1314
