### ISSUE TITLE
The repository 'https://deb.nodesource.com/node_14.x bionic Release' does not have a Release file.

### ISSUE THREAD

**Issue by bsamadi** [jupyterhub/repo2docker#1090]
### Bug description

I am using repo2docker version 2021.08.0. When I run `repo2docker .` in my repository, I get the following error:
`The repository 'https://deb.nodesource.com/node_14.x bionic Release' does not have a Release file.`

When I open my repository using mybinder.org, the docker image is made successfully

#### Expected behaviour

The docker image is made.
#### Actual behaviour

The docker image built process fails with this error:
`The repository 'https://deb.nodesource.com/node_14.x bionic Release' does not have a Release file.`
### How to reproduce

1. Install repo2docker on Ubuntu 20.04: `pip install jupyter-repo2docker`
2. Clone this repository: `git clone https://github.com/eLearningHub/pdf2video.git`
3. Go the main folder: `cd pdf2video`
4. Run: `repo2docker .`

### Your personal set up

 - OS: Ubuntu 20.04
 - Docker version: `docker version` 
```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu1~20.04.1
 Built:             Wed Aug  4 22:52:25 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu1~20.04.1
  Built:            Wed Aug  4 19:07:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.2-0ubuntu1~20.04.2
  GitCommit:        
 runc:
  Version:          1.0.0~rc95-0ubuntu1~20.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
```
 - repo2docker version `repo2docker --version` 
2021.08.0

**Comment by bsamadi** [comment]
I also tried it on Ubuntu 18 and got the same error.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/node-14-x-bionic-release-does-not-have-a-release-file/11048/2

**Comment by bsamadi** [comment]
https://github.com/nodesource/distributions/issues/1266#issuecomment-931597235

**Comment by matthew-brett** [comment]
Sorry - just checking - where is the right place to discuss this?  Should we be adding to the thread at https://discourse.jupyter.org/t/node-14-x-bionic-release-does-not-have-a-release-file/11048/2 ?

**Comment by manics** [comment]
@matthew-brett yes, please follow/update that thread

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/node-14-x-bionic-release-does-not-have-a-release-file/11048/8
