### ISSUE TITLE
Failure while creating an image when declaring apt.txt

### ISSUE THREAD

**Issue by akielbowicz** [jupyterhub/repo2docker#1091]
Hi, I just want to leave a trace of the issue for future reference.

Since yesterday (30/09/2021) when trying to open a Binder instance for a repository that specifies a `apt.txt` file it fails during the creation of the docker image with the following message

```bash
Step 40/52 : RUN apt-get -qq update && apt-get install --yes --no-install-recommends cowsay && apt-get -qq purge && apt-get -qq clean && rm -rf /var/lib/apt/lists/*
 ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
 ---> Running in b3fdf108dc4b
E: The repository 'https://deb.nodesource.com/node_14.x bionic Release' does not have a Release file.
Removing intermediate container b3fdf108dc4b
The command '/bin/sh -c apt-get -qq update && apt-get install --yes --no-install-recommends cowsay && apt-get -qq purge && apt-get -qq clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100Built image, launching...
Failed to connect to event stream
```

Specifically its failing due to this 
```bash
E: The repository 'https://deb.nodesource.com/node_14.x bionic Release' does not have a Release file.
```

Searching a bit seems that is something that happens not so often and is related to certificates as mentioned on this [issue](https://github.com/nodesource/distributions/issues/541#issuecomment-931437650) on the **nodesource/distributions** repo.

This seems that it's something very tangential, what should be a solution for this??
I guess that creating a docker image, publish it and then use that on the repo will be the safest way to handle. But seems like a bit complicated for someone not familiar with that. Is there a simpler way to overcome it? 

Thanks,

ps. I used a repo with just this to try it out:

`apt.txt` content
```
cowsay
```

**Comment by manics** [comment]
See https://discourse.jupyter.org/t/node-14-x-bionic-release-does-not-have-a-release-file/11048/6
Pulling the latest version of `buildpack-deps:bionic` should fix things.
