### ISSUE TITLE
R tests are failing on main

### ISSUE THREAD

**Issue by manics** [jupyterhub/repo2docker#1109]
### Bug description

I merged jupyterhub/repo2docker#1104 followed by jupyterhub/repo2docker#1107, and in combination the tests are failing.... in hindsight I should've closed/reopened jupyterhub/repo2docker#1107 before merging to trigger an updated CI check.

@yuvipanda Do you want to have a look? Or shall we revert jupyterhub/repo2docker#1107 since it's the most recent PR so that CI is green and fix it later?

**Comment by yuvipanda** [comment]
Yep, let's revert that for now? I'll look on Monday 

Thanks for catching these!

**Comment by manics** [comment]
I opened a PR to revert #1107 (https://github.com/jupyterhub/repo2docker/pull/1110
) but the tests on that PR are failing so maybe there's a problem in #1104, even though the tests were definitely passing before I merged it :cry:
 
I'll leave things as they are for now.

**Comment by yuvipanda** [comment]
I can't seem to reproduce this locally unfortunately...

**Comment by yuvipanda** [comment]
Could be my cache, busting it now. Taking a while, haha :)

**Comment by yuvipanda** [comment]
@manics it looks like a transient MRAN outage. I re-ran the tests on main and it passed now.

**Comment by yuvipanda** [comment]
@manics this PR also passes: https://github.com/jupyterhub/repo2docker/pull/1110. I suspect it was an MRAN outage.

**Comment by manics** [comment]
Good thing you're replacing MRAN 😁
