### ISSUE TITLE
Is it possible to use repo2docker to customize a vm

### ISSUE THREAD

**Issue by picca** [jupyterhub/repo2docker#1125]
Hello, I would like to provision full vm and let users customize them with your configure system.

Can we use repo2docker from within a vm in order to modify a running system ?

if not, is it possible to run a docker image as a vm with qemu  or  convert a docker image into a full vm ?

thanks for considering.

**Comment by minrk** [comment]
Ultimately, repo2docker's output is a Dockerfile, which it then asks docker (or podman) to build. It cannot modify the host system. It's fine, though, to have a VM that mostly just runs just one container, though, if that's what you are after.

If you want folks to be able to customize actual VMs, though, repo2docker's not the right tool.

**Comment by picca** [comment]
> Ultimately, repo2docker's output is a Dockerfile, which it then asks docker (or podman) to build. It cannot modify the host system. It's fine, though, to have a VM that mostly just runs just one container, though, if that's what you are after.

thanks for the answer

> If you want folks to be able to customize actual VMs, though, repo2docker's not the right tool.

Do you know tools for this purpose ?

**Comment by manics** [comment]
FYI repo2docker has a pluggable engine. I had a go at generating shell scripts / packer files as an interesting exercise
https://github.com/manics/repo2shellscript

This is not suitable for production, nor is it in anyway supported, but it might give you some ideas, which came out of this Discourse discussion: https://discourse.jupyter.org/t/brainstorming-repo2docker-action-vm-on-gcp-aws-azure/5345

Shall we close this issue and continue the conversation there?
