### ISSUE TITLE
Customize base build image via build args

### ISSUE THREAD

**Issue by holzman** [jupyterhub/repo2docker#1138]
Currently, the base image is hardcoded to buildpack-deps:bionic. 

It's a good idea to customize this - particularly to point at registry cache to avoid dockerhub pull limits (and cleaner than modifying the configuration to use a different default registry).

I can push a relatively straightforward patch if that's OK

**Comment by manics** [comment]
This is a duplicate of https://github.com/jupyterhub/repo2docker/issues/487
Please feel free to add any additional information or ideas there!
