### ISSUE TITLE
tidyverse loading difference between JupyterLab and RStudio

### ISSUE THREAD

**Issue by pierrepo** [jupyterhub/repo2docker#1153]
### Bug description

The R package `tidyverse` loads successfully in JupyterLab but fails in RStudio.

We use as an example [this repository](https://github.com/plasmabio/template-r/) that contains the description of a R environment with the `tidyverse` package installed with conda.

#### Expected behaviour

The R instruction

```r
library(tidyverse)
```
should work without any error.

#### Actual behaviour

In JupyterLab, we can load `tidyverse` both in a R notebook:

![image](https://user-images.githubusercontent.com/733861/164316464-d38ae2c9-5add-4c1d-92f2-a68d7b8d205a.png)

and in a terminal:

![image](https://user-images.githubusercontent.com/733861/164316671-9d6369b7-2895-4c68-9127-a9a5c4f0acf4.png)

In RStudio, this fails:

![image](https://user-images.githubusercontent.com/733861/164316990-f7c71761-ae6b-494b-8871-64b350f6228f.png)

For debugging purpose, here is the output of the `sessionInfo()` instruction:
```r
R version 4.1.3 (2022-03-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

Matrix products: default
BLAS/LAPACK: /srv/conda/envs/notebook/lib/libopenblasp-r0.3.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] fansi_1.0.3     utf8_1.2.2      digest_0.6.29   crayon_1.5.1   
 [5] IRdisplay_1.1   repr_1.1.4      lifecycle_1.0.1 jsonlite_1.8.0 
 [9] evaluate_0.15   pillar_1.7.0    rlang_1.0.2     cli_3.2.0      
[13] uuid_1.1-0      vctrs_0.4.1     ellipsis_0.3.2  IRkernel_1.2   
[17] tools_4.1.3     glue_1.6.2      fastmap_1.1.0   compiler_4.1.3 
[21] base64enc_0.1-3 pbdZMQ_0.3-7    htmltools_0.5.2
```

### How to reproduce

Create an environment with `repo2docker` and [this repository](https://github.com/plasmabio/template-r/).

Try to run the R command:
```r
library(tidyverse)
```

You are sure `tidyverse` is loaded correctly when you can run this second command also without error:
```r
as_tibble(mtcars)
```

### Your personal set up

 - OS: Linux Ubuntu 20.04
 - Docker version: 20.10.14, build a224086
 - repo2docker version: 2022.02.0+19.g1d218af

### A possible lead (or not)

I suspect an issue with the availability of C++ libraries.

In a terminal, in RStudio, I have:
```bash
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX_3.4.26
$ strings /srv/conda/envs/notebook/lib/libstdc++.so.6 | grep GLIBCXX.3.4.26
GLIBCXX_3.4.26
GLIBCXX_3.4.26
```
So, I guess R within RStudio should have access to `/srv/conda/envs/notebook/lib/libstdc++.so.6` rather to `/usr/lib/x86_64-linux-gnu/libstdc++.so.6` only.

What puzzles me is that in RStudio we have:

```r
> Sys.getenv("LD_LIBRARY_PATH")
[1] "/srv/conda/envs/notebook/lib/R/lib"
```

but in JupyterLab we have:

```r
> Sys.getenv("LD_LIBRARY_PATH")
[1] ""
```
So this lead could be wrong...

**Comment by SylvainCorlay** [comment]
I was talking to @pierrepo earlier, and this seems quite important!

**Comment by pierrepo** [comment]
Apart displaying the content of env variables such as `LD_LIBRARY_PATH`, I don't know how to explore the content of environments in JupyterLab or RStudio.

A more radical solution would be to update the system `libstdc++.so.6` to a more recent version, such as explaining [here](https://github.com/LedgerHQ/ledger-live-desktop/issues/4016#issuecomment-889455692) but I don't think we can have ppa in repo2docker.

**Comment by manics** [comment]
Some relevant information in https://discourse.jupyter.org/t/openssl-mismatch-between-rstudio-and-conda-environments/14123/

**Comment by pierrepo** [comment]
There is an ongoing PR about the way RStudio is installed within repo2docker: https://github.com/jupyterhub/repo2docker/pull/1161
This might solve our problem here.

**Comment by nasiegel88** [comment]
I ran into a similar issue with tidyverse not loading in rstudio. I was told this can be resolved by adding `start` to your working directory, with the contents:
```bash
#!/bin/bash

set -e

export LD_LIBRARY_PATH=${NB_PYTHON_PREFIX}/lib:${LD_LIBRARY_PATH}
```
*note: you may need to make it executable with `chmod u+x start`

I am not sure why this works but I include this in all my R repos that use repo2docker.

**Comment by pierrepo** [comment]
Thanks for your input @nasiegel88 :pray: 
I did some tests [here](https://github.com/plasmabio/template-r/tree/fix-tidyverse-install) that were unsuccessful. Would you mind sharing an example repo of yours?

**Comment by manics** [comment]
Do you know what the underlying problem is? Is it safe to always set this when running rstudio? If so we could perhaps do this automatically in repo2docker by passing additional environment variables to https://github.com/jupyterhub/jupyter-rsession-proxy. We'd need to be confident it won't break some other R packages though!

**Comment by fkohrt** [comment]
I am having a related issue when running Shiny apps:

Starting a Shiny app from within RStudio...

```r
install.packages(c("leaflet", "shinydashboard", "dplyr", "curl"))
options(warn = 1)
shiny::runApp("r/bus-dashboard")
```

...leads to the following error:

```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/srv/conda/envs/notebook/lib/R/library/Rcpp/libs/Rcpp.so':
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /srv/conda/envs/notebook/lib/R/library/Rcpp/libs/Rcpp.so)
```

I tried installing `libstdc++6` and `gcc-8` via `apt.txt`, but that didn't help. The Shiny interface at `/shiny/r/bus-dashboard/` does work, however, as does running the code above from JupyterLab.

Here's a repository for you to check: [`gitlab.com/fkohrt/binder-test`](https://gitlab.com/fkohrt/binder-test)

[![Binder](https://mybinder.org/badge_logo.svg)](https://gke.mybinder.org/v2/gl/fkohrt%2Fbinder-test/main?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fbinder-examples%252Fr%26urlpath%3Drstudio%252F%26branch%3Dmaster)

Most important, this is only an issue when using `environment.yml` to install R:

```yml
channels:
  - conda-forge
dependencies:
  - python
  - nbgitpuller
  - r-base
```

If I use `requirements.txt` instead, none of the issues are present – I can do `library(tidyverse)` and `shiny::runApp("r/bus-dashboard")` without any problems, but now the Shiny interface at `/shiny/r/bus-dashboard/` does not work (`An error has occurred!`). This can be verified with the following repository: [`gitlab.com/fkohrt/RMarkdown-sandbox`](https://gitlab.com/fkohrt/RMarkdown-sandbox)

[![Binder](https://mybinder.org/badge_logo.svg)](https://gke.mybinder.org/v2/gl/fkohrt%2FRMarkdown-sandbox/main?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fbinder-examples%252Fr%26urlpath%3Drstudio%252F%26branch%3Dmaster)
