### ISSUE TITLE
Supported Python versions in FAQ differ from setup.py & README

### ISSUE THREAD

**Issue by zaneselvans** [jupyterhub/repo2docker#1154]
### Bug description
The [FAQ](https://github.com/jupyterhub/repo2docker/blob/main/docs/source/faq.rst) says that `repo2docker` is compatible with Python 2.7, 3.5, 3.6, and 3.7. But the `setup.py` and `README` say it requires Python 3.6+. It seems like the FAQ is out of date, but maybe there are different versions of Python being run in different contexts? I wasn't confident enough to propose a change to the FAQ, but it seemed like something either needed to be updated or explained in more detail.

#### Expected behaviour
I expected that the docs would indicate the same Python version compatibility everywhere.

#### Actual behaviour
FAQ and README/setup.py seem to indicate different Python versions should be expected to work.

**Comment by manics** [comment]
The repo2docker application runs on Python 3.6 as indicated in the README, but it can build containerised environments using older version of Python such as 2.7 which is what the FAQ refers to. If you think it's unclear please open a PR to improve the language. Thanks!
