### ISSUE TITLE
Cannot launch notebook from Dataverse

### ISSUE THREAD

**Issue by wilhelmfrank** [jupyterhub/repo2docker#1170]
even after a successful pull request https://github.com/jupyterhub/repo2docker/pull/1167
we're still not able to access notebooks from our Dataverse instance via https://mybinder.org/:

Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockeryz1hri60'...
error: cannot run ssh: No such file or directory
fatal: unable to fork
Error during build: Failed to clone repository from doi:10.17617/3.QLWR38 (ref 193401.v1.0).

please see screenshot.
![image](https://user-images.githubusercontent.com/7069622/181455472-d58eb149-9724-4f18-8885-af03cee734b8.png)

**Comment by manics** [comment]
I've just merged https://github.com/jupyterhub/mybinder.org-deploy/pull/2307
which is the mybinder.org PR containing a repo2docker update. The deployment pipeline is currently running, when it completes the PR you referenced should be deployed.

**Comment by wilhelmfrank** [comment]
Thanks! It's all working fine now.
