### ISSUE TITLE
Cannot build an image with `buildpack-deps:bionic`

### ISSUE THREAD

**Issue by mrakitin** [jupyterhub/repo2docker#1221]
It's not possible to build an image with repo2docker due to the missing package repositories for ubuntu/bionic.

### Bug description
This line causes errors while attempting to install packages with `apt-get` while building an image with `repo2docker`:
https://github.com/jupyterhub/repo2docker/blob/b6098c02f315a37d690a0c538973de53dd0631a3/repo2docker/buildpacks/base.py#L16

#### Expected behavior

The CI build should succeed.

#### Actual behavior
```
   ...
   ---> 8078583bc546
  Step 3/52 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends locales > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
   ---> Running in c73d5a674d8c
  E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/restricted/binary-amd64/Packages  403  Forbidden [IP: 185.125.190.39 80]
  E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/universe/binary-amd64/Packages  403  Forbidden [IP: 185.125.190.39 80]
  E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/main/binary-amd64/Packages  403  Forbidden [IP: 185.125.190.39 80]
  E: Some index files failed to download. They have been ignored, or old ones used instead.
  Removing intermediate container c73d5a674d8c
  The command '/bin/sh -c apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends locales > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

### How to reproduce

See the CI status at https://github.com/NSLS-II/scipy-binder/pull/57.

### Your personal set up

CI config of https://github.com/NSLS-II/scipy-binder.

**Comment by mrakitin** [comment]
@yuvipanda, should it be here or at https://github.com/jupyterhub/repo2docker-action?

**Comment by manics** [comment]
Does this error occurred all the time or does it fix itself after a few hours?

Do you see the same error if you install and run repo2docker locally?

**Comment by mrakitin** [comment]
Thanks for your reply, @manics! Indeed, looks like the issue was transient and disappeared after I restarted the CI job a couple of hours later. False alarm. Local builds passed that failing step.

It's probably still worth considering a newer ubuntu tag as bionic will be EOL pretty soon. Are there plans to use a newer base image?

**Comment by manics** [comment]
There are several discussions but although it's an easy code change it's a big breaking change:
- https://github.com/jupyterhub/repo2docker/pull/909
- https://github.com/jupyterhub/repo2docker/issues/1220

**Comment by mrakitin** [comment]
Thanks for the insights, @manics!
