### ISSUE TITLE
R on Binder: What happens if MRAN goes away?

### ISSUE THREAD

**Issue by andrewjohnlowe** [jupyterhub/repo2docker#1240]
Apologies if this is a naive question, but here goes...

The documentation that describes configuring Binder to install R packages states that daily snapshots of CRAN that are hosted on MRAN are used. So what happens if MRAN disappears? More specifically, what dependencies are there on MRAN? Where are all the places it is used?

I want to setup my repo to trigger a `packrat` restore from a lock file instead of using MRAN. This provides better control over package versions (I've had problems, albeit rare, in the past when using `checkpoint`). Also, `packrat` works with packages installed from GitHub and BioConductor. I've already got this working locally, but not with Binder.

**Comment by manics** [comment]
What's the current best practice recommended by the R community for reproducibility?

**Comment by annakrystalli** [comment]
I'd say package [`renv`](https://rstudio.github.io/renv/) which represents the evolution of package `packrat` discussed earlier in this issue would be most appropriate.

**Comment by sgibson91** [comment]
I think we have now officially switched over to the Posit Package Manager system and this issue can be closed.

- https://github.com/jupyterhub/repo2docker/pull/1104
- https://github.com/jupyterhub/repo2docker/pull/1285
