### ISSUE TITLE
Dataverse content provider: download files in original format

### ISSUE THREAD

**Issue by pdurbin** [jupyterhub/repo2docker#1242]
### Proposed change

Apologies for not considering this back when ❤️ @Xarthisius ❤️  added the Dataverse content provider back in...

- #739

... but now that we've enabled the Binder button in Harvard Dataverse 🎉 🎉 🎉 ...

- https://github.com/IQSS/dataverse.harvard.edu/issues/208

... I'm thinking we should teach repo2docker to always download the ORIGINAL format of files rather what we're doing now.

In short, rather than downloading a file using this URL:

`https://dataverse.harvard.edu/api/access/datafile/3323458`

We'd like to download the file with this URL instead:

`https://dataverse.harvard.edu/api/access/datafile/3323458?format=original`

Using the Stata file above as an example (which I found in a comment in dataverse.py), this will instruct Dataverse to download the original `calendarmonth_fires_SPstate.dta` version of the file rather than the archive-friendly tab delimited version `calendarmonth_fires_SPstate.tab` that Dataverse creates automatically.

### Alternative options

This is really in the Dataverse weeds but we could work on this to solve perf problems (but not UX problems):

- https://github.com/IQSS/dataverse/issues/8524

### Who would use this feature?

The main users of this feature would be people who are trying to write scripts to reproduce results. Locally on their laptops, they're probably writing scripts to operate on their original file (`calendarmonth_fires_SPstate.dta`) and are surprised that Binder or Whole Tale are presenting the derived, archival version instead  (`calendarmonth_fires_SPstate.tab`).

The other users are sysadmin who are noticing perf problems related to that 8524 issue above (again, details you probably don't need to worry about).

### How much effort will adding it take?

`?format=original` is only adding 16 characters but let's say a day for testing, etc.

### Who can do this work?

Oh, I could probably do it. Or someone else on the Dataverse team. Or @Xarthisius if he's up for it.

Should one of us go ahead and make a pull request? Please let us know! Thanks.

**Comment by betatim** [comment]
Thanks for filing the issue. It seems like a good idea, I think users would be surprised to find the format of the data to be different in their binder compared to what they uploaded. If you have time to create a PR that would be great.

**Comment by pdurbin** [comment]
@betatim great, thanks! I just created this issue to track the work on our side:

- https://github.com/IQSS/dataverse/issues/9374

I'll work on getting it into a sprint.

**Comment by pdurbin** [comment]
I just created a pull request to fix this issue:

- #1253

I tried to follow https://repo2docker.readthedocs.io/en/latest/contributing/contributing.html#guidelines-to-getting-a-pull-request-merged best I could! 😅 

Oh, shoot, I forgot to add `[MRG]` to the title. Will fix. I did try to explain the "why" in the commit message, at least. 😄

**Comment by pdurbin** [comment]
> Locally on their laptops, they're probably writing scripts to operate on their original file (`calendarmonth_fires_SPstate.dta`) and are surprised that Binder or Whole Tale are presenting the derived, archival version instead (`calendarmonth_fires_SPstate.tab`).

Now @minrk merged my pull request...

- #1253 

... this had been fixed! Thank you!!

Here's how [that dataset](https://doi.org/10.7910/DVN/3MJ7IR) looks in Dataverse. Note that the .tab versions (the plain text archival versions) are shown in the UI. We click the Binder button...

![Screen Shot 2023-03-29 at 10 01 31 AM](https://user-images.githubusercontent.com/21006/228565130-ba050bff-3985-4ab6-a646-17d7b28e2439.png)

... wait a bit...

![Screen Shot 2023-03-29 at 10 02 49 AM](https://user-images.githubusercontent.com/21006/228565208-94c256be-d28d-45d6-9822-56ea9f0e6661.png)

... and in Binder we can now see and operate on the original Stata (.dta) files!

![Screen Shot 2023-03-29 at 10 03 59 AM](https://user-images.githubusercontent.com/21006/228565400-89bade9f-68ec-404f-b863-0d4afecacfb2.png)
