### ISSUE TITLE
Update  to a more recent version : repo2docker/buildpacks/base.py l:16 FROM buildpack-deps:bionic 

### ISSUE THREAD

**Issue by ptempier** [jupyterhub/repo2docker#1258]
### Proposed change

Switch to a more recent default buildpack than bionic (5Years old)

### Alternative options

For compatibility/legacy  reason, Allow selection of the buildpack

### Who would use this feature?

Proposed change would impact the default buildpack, so i guess a lot of peoples ?

### How much effort will adding it take?

Easy to add, hard to test.

### Who can do this work?

Simple change, it s only a few charcters to change.

Then there's a need to test it
- Not sure if the project has non regression tests, in that case it's simple
- If there's no non regression test, then need to find relevant test cases.

**Comment by manics** [comment]
We definitely need to do this, but it's also a massive breaking change for anyone using `apt.txt` to install packages, since these packages may have breaking changes, or be added/removed/renamed.

**Comment by ptempier** [comment]
👍
