### ISSUE TITLE
Can not use r2d as a library

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/repo2docker#126]
Per https://github.com/jupyter/repo2docker/pull/120#issuecomment-340382310 from @betatim (who actually tests things before making proclamations!):

Currently you can't use `repo2docker` as a library:
```python
import repo2docker.app
app = repo2docker.app.Repo2Docker()
app.initialize()
```
gives you the somewhat confusing:
```
usage: ipython [-h] [--config CONFIG] [--json-logs] [--image-name IMAGE_NAME]
               [--ref REF] [--debug] [--no-build] [--no-run] [--no-clean]
               [--push]
               repo ...
ipython: error: the following arguments are required: repo, cmd
An exception has occurred, use %tb to see the full traceback.
```
which just makes me think "ipython????" :) What magic sauce do we need to add to deal with the traitlets?

**Comment by yuvipanda** [comment]
I ran into this again, working on github.com/jupyterhub/hubploy

Few things we can do here:

1. Use SystemExit less liberally
2. No print statements, only logging entries

**Comment by yuvipanda** [comment]
https://github.com/jupyter/repo2docker/pull/496 is part 1 - it splits up argument parsing into a separate file.

Next step is to try remove all `print` statements and `SystemExit` exceptions from anywhere other than `main()`

**Comment by manics** [comment]
Has this been fixed?

**Comment by yuvipanda** [comment]
Yeah, we can re-open this if there are more specific problems.
