### ISSUE TITLE
curl-48-an-unknown-option-was-passed-in-to-libcurl

### ISSUE THREAD

**Issue by tschm** [jupyterhub/repo2docker#1266]
### Bug description

Problem with curl if using ubuntu-latest

### How to reproduce

1. Go to https://github.com/tschm/cs and inspect the failing workflow

**Comment by willow-ahrens** [comment]
I hit this bug as well on my repo, I set continue-on-fail so it looks green for now, but the action did indeed fail with the same bug.

**Comment by tschm** [comment]
This is discussed here https://github.com/jupyterhub/repo2docker-action/issues/99
