### ISSUE TITLE
timeframe for updating `main`/2023.06.0 tag to point at `latest`?

### ISSUE THREAD

**Issue by shaneknapp** [jupyterhub/repo2docker#1292]
one of our projects (using the `repo2docker-action` to enable testing of notebooks) is currently on hold as we're waiting for the `main` tag to point to `latest`/2023.06.0.

the reason why it's on hold is that the [`repo2docker-action` Dockerfile](https://github.com/jupyterhub/repo2docker-action/blob/master/Dockerfile#L1) points to `main`, and we need the functionality of v2023.06.0 https://github.com/jupyterhub/repo2docker/pull/909 (particularly defining the `FROM <base_image>` in our z2h deployment.

is there a roadmap for this?  thanks in advance!

**Comment by yuvipanda** [comment]
<img width="591" alt="image" src="https://github.com/jupyterhub/repo2docker/assets/30430/97944bb1-9cc4-408c-b189-79781ad8d0c3">

I think `main` now points to latest, @shaneknapp!
