### ISSUE TITLE
--base-image not recognise as valid argument

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/repo2docker#1295]
Related with https://github.com/jupyterhub/repo2docker/issues/487

https://github.com/jupyterhub/repo2docker/blob/247e9535b167112cabf69eed59a6947e4af1ee34/repo2docker/app.py#L450 should make `--base-image` a valid argument for `repo2docker` but I'm getting

```
repo2docker: error: unrecognized arguments: --base-image
```

with

```
$ repo2docker --version
2023.06.0
```

**Comment by manics** [comment]
It's a traitlet, so try `--Repo2Docker.base_image=...`

Run `repo2docker --help-all` to see the full list

**Comment by rgaiacs** [comment]
Thanks! `--Repo2Docker.base_image=...` works for me.
