### ISSUE TITLE
Discuss `binder.yaml` files and what to support

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/repo2docker#166]
In the Binder repo we discussed a way to let users specify their distribution (e.g. artful vs. zesty). It was decided that a `binder.yaml` file would be a good way to do this. Let's use this issue to see what kind of functionality we want to support in this file.

**Comment by betatim** [comment]
There is also https://github.com/jupyterhub/binder/issues/42 on `binder.yml` ideas

**Comment by betatim** [comment]
https://github.com/jupyter/repo2docker/pull/148 discusses letting the user choose a base image, could also be done with a `bidner.yml`

**Comment by yuvipanda** [comment]
A binder.yaml should be nothing more than something like:

```
apt.yaml:
    <contents of what would have been in apt.yaml>
requirements.txt:
    <contents of what would have been in environment.yaml>
```

We can implement it by simply exploding this into multiple files and then running normal repo2docker process. This also means we don't invent a new format.

I really wanted us to invent a new format when we started, but @willingc, @minrk and @choldgraf convinced me that we'll just be re-inventing a shitty Ansible :)

**Comment by choldgraf** [comment]
a question I'm still unsure about: will there be *any* functionality in a `binder.yaml` file that can't also be accessed via a corresponding configuration file? E.g., would it be possible to specify a specific environment variable (e.g., `distribution: artful`) in a binder.yaml file, but not have a config file with which you could do the same thing. On the one hand this makes things more confusing, on the other it might reduce the number of config files in general that people need to use.

**Comment by betatim** [comment]
What are the features we are missing right now that would need us to invent a way to set them? I am strongly in favour of not having a `binder.yaml`, using @yuvipanda's proposal is Ok to me.

Things I can remember that we don't support currently and users have asked for:
* setting ENV variables
* specifying/pinning the base image

**Comment by choldgraf** [comment]
Those are the two I can think of as well, though I'm sure we'll have more pop up over time as well.

**Comment by mukundans91** [comment]
It seems that this discussion at least the initial half coincides with a lot of what was said in #148.  But if a feature is made to allow users to determine the base image of docker(zesty or artful), then the onus for maintaining basic compatibility with those images comes into the picture as well. How to make sure that the user specified version does not break the current set of tests and basic functionality?

Another question is will there be requests to support other linux distros as well?

**Comment by choldgraf** [comment]
I think those are all good questions, IMO users should be responsible for making sure their code etc runs the way they want on those base distributions...we should only make it possible to select them.

The more I think about it, the more I like the idea of having a strict "everything in `binder.yaml` must also be possible to specify in its own standalone file". That way as @yuvipanda describes we could just parse `binder.yaml`, create a file for each entry, then run r2d on the generated files.

**Comment by minrk** [comment]
I think specifying the base image essentially needs to freeze the template and buildpack versions (basically everything), since it has cascading compatibility issues for every buildpack, and it will not likely work to guarantee going forward that all buildpacks support all available distros without adding `if distro == 'x': do old thing` switches over time.

I'm not sure there's a good way to achieve that, though.

**Comment by psychemedia** [comment]
Could a `binder.yaml` file have a role to play in mitigating against breakages introduced by updates to (possibly?) `repo2docker`, eg as per https://github.com/binder-examples/latex/issues/2 ?

Are there any tools that let you compare two different environments (installed packages, environment variables, etc?) If so, what do they generate to capture a particular environment and could a binderhub image builder generate such a log file that a user could then copy/save as a reference statement of a particular environment?

**Comment by manics** [comment]
[This cool sounding project](https://github.com/dorgeln/orbiter) popped up on the Discourse today: https://discourse.jupyter.org/t/orbiter-image-builder-for-jupyter/9216

Shall we close this issue and continue the discussion on Discourse where there may be more general input? Or would you prefer to keep this open?

**Comment by consideRatio** [comment]
Since this issue is stale and I couldn't conclude a clear action point, I'll go for a close at this point.
