### ISSUE TITLE
Javascript builds

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/repo2docker#25]
We also need to support dependencies for Javascript (maybe including things that require a function call after installing, e.g. some of the jupyter extensions?). Discuss implementations etc here!

Note that our guide on repo2docker already starts out by showing how to create a builder with `npm`. Perhaps we can create a javascript build in parallel with finishing that document.

**Comment by choldgraf** [comment]
just a thought: should we just capture this with `postBuild`?

**Comment by manics** [comment]
If this is purely for jupyter extensions it could be part of https://github.com/jupyterhub/repo2docker/issues/868 ?

**Comment by consideRatio** [comment]
Hey, starting out some triaging - this is the oldest issue open in repo2docker and seems to me like something not worth supporting without a stronger pull for it.

I'll go for a close at this point
