### ISSUE TITLE
Investigate the use of conu for testing

### ISSUE THREAD

**Issue by willingc** [jupyterhub/repo2docker#266]
[Conu](https://developers.redhat.com/blog/2018/03/07/introducing-conu-scripting-containers-made-easier/?imm_mid=0fc12e&cmp=em-prog-na-na-newsltr_20180317) is a Python library for container tests.
http://conu.readthedocs.io/en/latest/

**Comment by betatim** [comment]
Similar/related library https://github.com/GoogleContainerTools/container-structure-test

I think we should switch from our home made pytest + verify setup. It is hard to see the error messages with what we have now which makes it hard to debug failures and we don't have a huge amount of docs on how to write tests which means we don't write as many as we should. Which in turn leads to problems like #371

**Comment by willingc** [comment]
@betatim Makes sense. Can we enable container-structure-test alongside Travis to see you it goes?

**Comment by betatim** [comment]
I think you install a separate binary for CST (container structure test), so it becomes one more thing travis runs for us. I like the idea of running it in parallel as it means we can slowly transition by adding CST tests as we go along and can keep the existing ones.

**Comment by manics** [comment]
I'm guessing that since it's been a few years no-one plans to do this? Shall we close this, or do you want to keep it as a reminder?
