### ISSUE TITLE
local builds should respect .gitignore ?

### ISSUE THREAD

**Issue by spMohanty** [jupyterhub/repo2docker#268]
I somehow expected that when building a local repository, `repo2docker` will respect `.gitignore` and not package the ignored files/directories in the image itself.

The use case where this was inconvenient was, when I had a `data/` folder in my source code, which was ignored by `git` based on the pathspecs in `.gitignore`. 
The folder in my dev environment contained about 16gb of data in the `data/` folder, and `repo2docker` ended up copying over all that data into the image (and also because of [this issue](https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/base.py#L87), the actual image size ended up being around 35GB 😢  ).

**Comment by choldgraf** [comment]
hmm - this sounds like something that's out of scope for repo2docker...It sounds like this is a frustrating experience, but adding the logic to remove files specified in a `.gitignore` file feels like it'd be a hacky solution.

I think you'll have better luck if you temporarily move out the `data` folder before running `r2d` on the repo. That said, I'm not sure how common it is to keep a large chunk of data bundled with a git repository. Let's keep this issue open in case other people run into the same problem and we decide we want to re-consider this.

**Comment by betatim** [comment]
I like the idea of respecting `.dockerignore` as discussed in #269

**Comment by choldgraf** [comment]
ah yes - I think `.dockerignore` would be a nice pattern since it's already out there.
