### ISSUE TITLE
Cache intermediate docker layers on travis

### ISSUE THREAD

**Issue by betatim** [jupyterhub/repo2docker#310]
Some builds tests take a long time because they have to build our repo2docker "base" again and again.

Travis can cache files between builds however they explicitly mention docker images as something [not to cache](https://docs.travis-ci.com/user/caching/#Things-not-to-cache). I think the reasoning is that pulling them from docker hub is just as fast/slow. In our case we want to cache the intermediate build layers.

What do people think about adding that and how it relates to Travis' wishes about docker image caching?

**Comment by minrk** [comment]
Worth a shot

**Comment by Madhu94** [comment]
Is this still relevant ?

**Comment by betatim** [comment]
Would be interesting to experiment with to find out if this speeds up our CI runs.

**Comment by manics** [comment]
I'll close this, we've got other issues related to caching and speeding up builds.
