### ISSUE TITLE
Feature: repo inspection summary

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/repo2docker#329]
Wouldn't it be good if a BinderHub user, after the selection of repo, could get some information presented about how repo2docker will act on the repo? repo2docker might for example ignore the requirements.yml's file in favor of the Dockerfile, or conclude that no repo2docker configuration file existed in the repo. Making such repo2docker conclusions available in the BinderHub UI might be valuable!

So, my suggestion is that repo2docker allows a --dry-run or similar option that suggests how it will act on the repo. The summary could for example declare what specific files it found and what it will care about. So the summary might say that it found a Dockerfile, a requirements.yml file and an environment.yml file and it will only care about the Dockerfile.

**Comment by choldgraf** [comment]
Interesting idea - some parts of this (or at least as less-nicely-formatted version of this) could be accomplished with `--no-build` and `--debug`. I take it you're talking about something that's more user-friendly than this? I'd be +1 if it doesn't add much complexity beyond the current build process, but -1 if it means we'd have to add a lot of machinery to build these reports

**Comment by manics** [comment]
I'm going to close this, https://github.com/jupyterhub/repo2docker/issues/783 is related though that's also seen no progress
