### ISSUE TITLE
Doc Using Other Languages that aren't obvious from configs

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/repo2docker#341]
So Far I've seen binders that also use:

- LaTeX
- C++
- go
- Haskell 

Would be good to have links to this and also docs other Jupyter Kernels

**Comment by betatim** [comment]
Should we start a section like https://mybinder.readthedocs.io/en/latest/sample_repos.html this to collect these examples in?

**Comment by jzf2101** [comment]
Yes - we can also describe at a high level how they do what they did?

**Comment by manics** [comment]
I'm closing this as it's quite old, anyone is of course free to add examples!
