### ISSUE TITLE
Environment --env documentation unclear

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/repo2docker#345]
Based on conversation with @yuvipanda we should be clear if the environment variables belong to the docker VM or are the python environment.

**Comment by betatim** [comment]
What are environment variables that are part of a Python environment?

If you set an environment variable via the `--env` flag you are doing approximately the same as typing `export BLAH=FOO` into a terminal. It sets an environment variable that you can access from any of the processes running in the container.

**Comment by jzf2101** [comment]
So what would be a typical usecase in the r2d context? I've never seen it used on mybinder.org

**Comment by betatim** [comment]
You can't use it from BinderHub because it doesn't provide a way for the owner of the repository to configure what should be set.

I'd use it to pass various temporary things on from my shell to the inside of the container when running `repo2docker` locally. API tokens and such.
