### ISSUE TITLE
best practice for adding a private repo to the build?

### ISSUE THREAD

**Issue by neuromusic** [jupyterhub/repo2docker#359]
I have a python package in a private repo which I would like to specify as a dependency in my requirements.txt file.

I can add it to the file with...

```
allensdk>=0.14.5
neuroglia
-e git+ssh://git.github.com/AllenInstitute/visual_behavior_analysis.git@master#egg=visual-behavior
```

but then how do I get expose my local SSH credentials to the Docker container? 

Or is there a better way to do this?

**Comment by choldgraf** [comment]
That's a good question - this has come up a few times in the binderhub/jupyterhub world. You might have some luck asking around in the JupyterHub channel. Though perhaps this is something that could/should be built into repo2docker? e.g. a `--key=<mykey>` flag or something?

**Comment by manics** [comment]
I'm closing this as it's quite old, and there's been some work on supporting private repos (though it's still ongoing).
