### ISSUE TITLE
Have different jlab versions on r2d based on python version 

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/repo2docker#445]
Right now we have JupyterLab as one of the pinned versions by the original `environment.yml` but jupyterlab requires python 3.6 or above.  Are we ok with modifying `freeze.py` to change the version numbers? #438

**Comment by manics** [comment]
I'm going to close this as we're on JuoyterLab 3 now, and in general we can separate the UI environment from the kernel environment.
