### ISSUE TITLE
Easy way to run a single repo on your own cloud instance

### ISSUE THREAD

**Issue by betatim** [jupyterhub/repo2docker#480]
We want to provide really easy ways for users to run a github repo on their own AWS or gcloud or OpenStack whatever instance. It should ideally allow them to do persistent long term work on it, including pushing stuff back to GitHub. We can use cloud-init + packer to make this happen across clouds without too much work on our part.

We also have a responsibility to do this as securely as possible, rather than leaving random botnet invitations across the internet.

---

This is a copy of #37 which turned into a discussion about supporting a particular user.

**Comment by yuvipanda** [comment]
I wrote a small script for @rabernat to do this for a PANGEO stack image. We can adapt this to run repo2docker instead, and generalize to support other clouds. We could also develop a Web UI for this.

https://gist.github.com/yuvipanda/cb918977ba8db42c93f3db726e5cbca4 is the code right now.

**Comment by betatim** [comment]
This idea came up again in https://github.com/machine-learning-apps/repo2docker-action/issues/17#issuecomment-629999332.

I think we could take Yuvi's script as a base to build on. I am imagining something like `repo2docker-deploy google https://github.com/foo/bar` which would build the image and then launch it. Similar to datasette's `deploy` command it would assume you have credentials setup already.

I'd make it a separate command because we currently don't have any "sub-commands" for `repo2docker` and I think it would be tricky to start now while preserving the old CLI.

**Comment by psychemedia** [comment]
If you are starting with a separate command, would it make sense to check the datasette code to see if additional hosts are added via a plugin model, and if so, go with a similar model; there may be opportunities for either common code, or lots of cribs, when adding new hosts.

**Comment by manics** [comment]
Also see this Discourse discussion
https://discourse.jupyter.org/t/brainstorming-repo2docker-action-vm-on-gcp-aws-azure/5345

**Comment by manics** [comment]
Shall we close this, as any work would most likely be in a separate repo that depends on R2D?

**Comment by julianpistorius** [comment]
The [Exosphere project](https://gitlab.com/exosphere/exosphere) recently added a feature to launch Binder-compatible repositories on OpenStack virtual machines using a friendly GUI:
<img width="824" alt="exosphere-and-binder-01" src="https://user-images.githubusercontent.com/742633/133660950-1bd00ef3-1e30-4a85-9616-1740a227d72f.png">
<img width="824" alt="exosphere-and-binder-02" src="https://user-images.githubusercontent.com/742633/133660956-a850bb0a-1c9f-469b-b5cd-02eab441f1c3.png">

See <https://youtu.be/07t9pTtoCxM> for a demo.

Under the hood we use `repo2docker` to build and launch a container from a repository, grab the authentication token, and create a link to access Jupyter/RStudio through an HTTPS reverse proxy.

If you have a Jetstream allocation you can try it yourself with the Jetstream-branded Exosphere: <https://exosphere.jetstream-cloud.org/>

Note: For now you have to enable 'experimental features' in settings to see this feature. 

Let us know what you think, as well as questions and suggestions for improvement.

Background: Exosphere is an open source client for cloud computing, focused on OpenStack at the moment. It's written in [Elm](https://elm-lang.org/) and is deployed as a [single-page application (SPA)](https://en.wikipedia.org/wiki/Single-page_application). There are no server-side components (except for a couple of simple reverse proxies to work within browser security restrictions). See the repository for the full source code and information on how to get started: <https://gitlab.com/exosphere/exosphere>

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/brainstorming-repo2docker-action-vm-on-gcp-aws-azure/5345/23

**Comment by manics** [comment]
The last release added support for implementing your own `ContainerEngine` instead of Docker: https://repo2docker.readthedocs.io/en/latest/changelog.html#version-2021-08-0

In theory you could create a subclass to spin up a cloud VM. I'm going to close this issue. If anyone makes more progress on this or wants to discuss it further please use [Discourse](https://discourse.jupyter.org/) where more people will be able to contribute to the discussion. Thanks!
