### ISSUE TITLE
Automatically run postBuild scripts to halt on error

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/repo2docker#503]
By default, bash scripts won't stop execution if they hit an error, they just keep on going. This could create a lot of confusing behavior for people in Binder, since it'd look like their bash script worked, but really nothing happened.

How can we ensure that a `postBuild` file that doesn't run properly **also** halts the build of an image? I think if we use `set -e`, it'll only **exit** the bash script on error, but then repo2docker will just continue with the next step...

cc @yuvipanda

**Comment by choldgraf** [comment]
Another option would be to encourage people to use a more friendly language (like python) for executing postBuild scripts by altering what comes after the `!#`. E.g. we could tell people how to execute postBuild with Python (`!#/usr/bin/env python3`), R, whatever.

**Comment by choldgraf** [comment]
so......I may have discovered that there wasn't actually an error happening, but that instead I was looping through an empty list which I was interpreting as an error........

anyway, it looks like if you have an error in postBuild (even without -e) then it will print an error message in red in the log output, but will still continue. Is that desired behavior?

**Comment by betatim** [comment]
Can you run the `postBuild` script by hand outside of repo2docker? If yes, check what the exit code is (run `echo $?` right after running the `postBuild` script in your terminal). If the exit code is 0 then docker will continue to run because the script signalled "all good, I ran to completion!".

I don't think we should start trying to guess from log messages whether or not the script might have not run properly. The exit code is the way to communicate that IMHO.

**Comment by betatim** [comment]
Whether or not the script stops running is up to the script. If you want a bash script to stop you need to put `set -e` in it.

The only thing we can do as the "executor" of the script is check the exit code (which should be != 0 if the script does not run to completion).

**Comment by yuvipanda** [comment]
@choldgraf is your script:

```bash
#!/bin/bash
gasdgasdg
```

or is it
```bash
#!/bin/bash
set -e
gasdgasdg
```

If it's the first one, it is expected that failure won't stop the build, since bash doesn't *actually* consider it an error. One solution there is to use a non-terrible language. If the following doesn't fail the build we have a problem:


```python
#!/usr/bin/env python3
asgasgdsag
```

**Comment by choldgraf** [comment]
I just ran this gist:

choldgraf/c7846cfa96bcfe8d186dff07da102ef0

with and without the `set -e` and in both cases this error happened:

![image](https://user-images.githubusercontent.com/1839645/50121061-68a4ba80-020c-11e9-8302-0be214f88a49.png)

so I can't reproduce this issue and I guess we should just close it :-/

**Comment by manics** [comment]
Closing as the last comment suggests it may not be a bug any more.
