### ISSUE TITLE
Configurable docker push timeout

### ISSUE THREAD

**Issue by betatim** [jupyterhub/repo2docker#711]
via https://discourse.jupyter.org/t/i-get-read-timed-out-errors-on-when-pushing-image-ovh/1394/7?u=betatim

Is there a way we can control/increase the timeout for the push operation at the end of the build? We are getting timeouts for this step on the OVH deployment and a potential way to help here is to increase (or make configurable) the push timeout.

The first step here is to find out how to control the timeout in the docker python client library we use.

**Comment by mael-le-gal** [comment]
I succeed in reproducing the error locally.

When we create a docker `docker.APIClient` there is a `timeout` parameter that we could give to the constructor.

Documentation say :

```
timeout (int): Default timeout for API calls, in seconds.
```

I let you now if changing this parameter fix the issue.

**Comment by mael-le-gal** [comment]
Indeed increasing that timeout fixed the issue.

The line of code is that [one](https://github.com/jupyter/repo2docker/blob/70819410f1d4cc2a31d82411646e141630e305be/repo2docker/app.py#L451)

It needs to be changed to something like that :  
```python
client = docker.APIClient(version="auto", timeout=CHOSEN_TIMEOUT, **kwargs_from_env())
```

Maybe this would be great to make it configurable. In this initial command line (like `--push-timeout xxx`) ?

**Comment by mael-le-gal** [comment]
Or by changing the `kwargs_from_env()` function to take the parameter from environment variables.

What do you think ?

**Comment by betatim** [comment]
Taking it from the environment sounds like a good idea to me. Mostly because we have a huge number of CLI flags already :-/ and my guess is this would be mostly used by deployments like BinderHub and not humans.

I think `kwargs_from_env()` is part of the docker-py library so maybe it already looks at an environment variable for this?

**Comment by mael-le-gal** [comment]
> Taking it from the environment sounds like a good idea to me. Mostly because we have a huge number of CLI flags already :-/ and my guess is this would be mostly used by deployments like BinderHub and not humans.

agree

> I think kwargs_from_env() is part of the docker-py library so maybe it already looks at an environment variable for this?

Indeed, I didn't saw that it was from `docker-py` but sadly the `timeout` parameter is not set in the function.

I'll then write my own function to get this parameter from env variables.

**Comment by betatim** [comment]
Something like this sounds like a good idea or maybe we can contribute to docker-py to get `kwargs_from_env()` changed?
```
def get_timeout():
  return value_from_env

client = docker.APIClient(version="auto", timeout=get_timeout(), **kwargs_from_env())
```
