### ISSUE TITLE
Fresh Python kernels for reliable builds.

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/repo2docker#741]
Programs managing python packages made available through configuration files with associated _lock files_, will probably regularly run into issues with conflicting dependencies that cannot be resolved. An example of such conflict arose around `certifi` (#725), a package that could not be successfully uninstalled by `pip` to be upgraded to the pinned version by the lock file that typically ends up doing these things.

I suggested a primitive workaround in #726, but this workaround had no guarantees to work and would certainly fail in a very complicated manner if it did fail. In short, it would pretend like the package was uninstalled before installing the new package, even though it wasn't, and override old files.

The most reliable solution I think, with performance drawbacks, is to always provide a fresh Python environment independent of the notebook server.

**Comment by manics** [comment]
Perhaps this could be done if we support decoupling the UI requirements from the user environment? https://github.com/jupyterhub/repo2docker/issues/868
