### ISSUE TITLE
repo2docker on Mac does not seem to be triggered by runtime.txt 

### ISSUE THREAD

**Issue by statOmics** [jupyterhub/repo2docker#833]
Dear all,

My GitHub pages with runtime.txt are working with online binder image. When I use repo2docker on my Mac,however, R is not installed in the docker. 

repo2docker --version
0.10.0

repo2docker does not seem to be triggered by runtime.txt file. I also tried with the binder/R examples on GitHub and that produces the same problem. See below

It seems as if the runtime.txt file is ignored. 

When a launch a terminal in docker R is not installed.

A requirements.txt, however, does trigger repo2docker to install additional python packages. 

It would be nice if somebody could give me some suggestions. 

Thx,

Lieven

Below the result and output of repo2binder for the binder/R example

<img width="1418" alt="Screenshot 2020-01-27 22 20 52" src="https://user-images.githubusercontent.com/24431387/73215055-a4ba8680-4153-11ea-82a7-7423b895c6af.png">

--- 

repo2docker r-master
Picked Local content provider.
Using local repo r-master.
Using PythonBuildPack builder
Step 1/46 : FROM buildpack-deps:bionic
 ---> 84f9345349b1
Step 2/46 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> b62ada79ed36
Step 3/46 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends locales > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> e203d07f5f9a
Step 4/46 : RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen &&     locale-gen
 ---> Using cache
 ---> 153d6ddf69cc
Step 5/46 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> eccf57315714
Step 6/46 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 40964b7fb480
Step 7/46 : ENV LANGUAGE en_US.UTF-8
 ---> Using cache
 ---> f03a5085f014
Step 8/46 : ENV SHELL /bin/bash
 ---> Using cache
 ---> 6c9c94ebecb2
Step 9/46 : ARG NB_USER
 ---> Using cache
 ---> 9b6dd9e87433
Step 10/46 : ARG NB_UID
 ---> Using cache
 ---> aef29fb24247
Step 11/46 : ENV USER ${NB_USER}
 ---> Using cache
 ---> ab0c2dca29e5
Step 12/46 : ENV HOME /home/${NB_USER}
 ---> Using cache
 ---> ae5fd21b8fff
Step 13/46 : RUN adduser --disabled-password     --gecos "Default user"     --uid ${NB_UID}     ${NB_USER}
 ---> Using cache
 ---> 83dcb944a4df
Step 14/46 : RUN wget --quiet -O - https://deb.nodesource.com/gpgkey/nodesource.gpg.key |  apt-key add - &&     DISTRO="bionic" &&     echo "deb https://deb.nodesource.com/node_10.x $DISTRO main" >> /etc/apt/sources.list.d/nodesource.list &&     echo "deb-src https://deb.nodesource.com/node_10.x $DISTRO main" >> /etc/apt/sources.list.d/nodesource.list
 ---> Using cache
 ---> 79e6722df7bc
Step 15/46 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends        less        nodejs        unzip        > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 89e3a695e530
Step 16/46 : EXPOSE 8888
 ---> Using cache
 ---> 1c8b4fd361eb
Step 17/46 : ENV APP_BASE /srv
 ---> Using cache
 ---> 714514dbe2dd
Step 18/46 : ENV NPM_DIR ${APP_BASE}/npm
 ---> Using cache
 ---> f8f712d0d460
Step 19/46 : ENV NPM_CONFIG_GLOBALCONFIG ${NPM_DIR}/npmrc
 ---> Using cache
 ---> eab7ef867f65
Step 20/46 : ENV CONDA_DIR ${APP_BASE}/conda
 ---> Using cache
 ---> f8519a0ba4cd
Step 21/46 : ENV NB_PYTHON_PREFIX ${CONDA_DIR}/envs/notebook
 ---> Using cache
 ---> f44421ad4249
Step 22/46 : ENV KERNEL_PYTHON_PREFIX ${NB_PYTHON_PREFIX}
 ---> Using cache
 ---> ea12033099ce
Step 23/46 : ENV PATH ${NB_PYTHON_PREFIX}/bin:${CONDA_DIR}/bin:${NPM_DIR}/bin:${PATH}
 ---> Using cache
 ---> 70cec40fc4ca
Step 24/46 : COPY conda/activate-conda.sh /etc/profile.d/activate-conda.sh
 ---> Using cache
 ---> 551d6a56d88b
Step 25/46 : COPY conda/environment.py-3.7.frozen.yml /tmp/environment.yml
 ---> Using cache
 ---> 02e39df1ff44
Step 26/46 : COPY conda/install-miniconda.bash /tmp/install-miniconda.bash
 ---> Using cache
 ---> a86a5c38a1c1
Step 27/46 : RUN mkdir -p ${NPM_DIR} && chown -R ${NB_USER}:${NB_USER} ${NPM_DIR}
 ---> Using cache
 ---> 19dba8681e18
Step 28/46 : USER ${NB_USER}
 ---> Using cache
 ---> 50efae515e37
Step 29/46 : RUN npm config --global set prefix ${NPM_DIR}
 ---> Using cache
 ---> f73f2af578dd
Step 30/46 : USER root
 ---> Using cache
 ---> a8f5909b39e2
Step 31/46 : RUN bash /tmp/install-miniconda.bash && rm /tmp/install-miniconda.bash /tmp/environment.yml
 ---> Using cache
 ---> 0e3400c1d218
Step 32/46 : ARG REPO_DIR=${HOME}
 ---> Using cache
 ---> c07c28f00251
Step 33/46 : ENV REPO_DIR ${REPO_DIR}
 ---> Using cache
 ---> c8a8b816c912
Step 34/46 : WORKDIR ${REPO_DIR}
 ---> Using cache
 ---> adc53223a121
Step 35/46 : ENV PATH ${HOME}/.local/bin:${REPO_DIR}/.local/bin:${PATH}
 ---> Using cache
 ---> f36c23ff1d1d
Step 36/46 : ENV CONDA_DEFAULT_ENV ${KERNEL_PYTHON_PREFIX}
 ---> Using cache
 ---> 5b8d748be101
Step 37/46 : USER root
 ---> Using cache
 ---> 2c194b1ace10
Step 38/46 : COPY src/ ${REPO_DIR}
 ---> 5cd78e0cc868
Step 39/46 : RUN chown -R ${NB_USER}:${NB_USER} ${REPO_DIR}
 ---> Running in 65ce1c7d37fc
Removing intermediate container 65ce1c7d37fc
 ---> f0d07c1ac1e4
Step 40/46 : LABEL repo2docker.ref="None"
 ---> Running in 1bd7d8168a4d
Removing intermediate container 1bd7d8168a4d
 ---> 6c48a2f412ad
Step 41/46 : LABEL repo2docker.repo="r-master"
 ---> Running in 631c2ad486ab
Removing intermediate container 631c2ad486ab
 ---> 1d1a486a5d27
Step 42/46 : LABEL repo2docker.version="0.10.0"
 ---> Running in c980902bca9f
Removing intermediate container c980902bca9f
 ---> 5632c4bafd07
Step 43/46 : USER ${NB_USER}
 ---> Running in c4b36510f8b8
Removing intermediate container c4b36510f8b8
 ---> 3ff8ebbf7e42
Step 44/46 : COPY /repo2docker-entrypoint /usr/local/bin/repo2docker-entrypoint
 ---> 5abb010a0c16
Step 45/46 : ENTRYPOINT ["/usr/local/bin/repo2docker-entrypoint"]
 ---> Running in 50e90ee4f554
Removing intermediate container 50e90ee4f554
 ---> cbc1779966b8
Step 46/46 : CMD ["jupyter", "notebook", "--ip", "0.0.0.0"]
 ---> Running in d9d13ec1f633
Removing intermediate container d9d13ec1f633
 ---> 31eced7e9099
{"aux": {"ID": "sha256:31eced7e90991d817e3a05a8307abea5573fb785d61918d90b2ac2c5be3052f9"}}Successfully built 31eced7e9099
Successfully tagged r2dr-2dmaster1580159763:latest
[I 21:16:17.037 NotebookApp] Writing notebook server cookie secret to /home/lclement/.local/share/jupyter/runtime/notebook_cookie_secret
[I 21:16:17.575 NotebookApp] JupyterLab extension loaded from /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab
[I 21:16:17.575 NotebookApp] JupyterLab application directory is /srv/conda/envs/notebook/share/jupyter/lab
[I 21:16:17.584 NotebookApp] nteract extension loaded from /srv/conda/envs/notebook/lib/python3.7/site-packages/nteract_on_jupyter
[I 21:16:17.588 NotebookApp] Serving notebooks from local directory: /home/lclement
[I 21:16:17.589 NotebookApp] The Jupyter Notebook is running at:
[I 21:16:17.589 NotebookApp] http://127.0.0.1:63055/?token=c2cd5876a4f29be0aab2286b979a30dc5985fa5194aa4a7d
[I 21:16:17.589 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 21:16:17.598 NotebookApp] No web browser found: could not locate runnable browser.
[C 21:16:17.599 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/lclement/.local/share/jupyter/runtime/nbserver-1-open.html
    Or copy and paste one of these URLs:
        http://127.0.0.1:63055/?token=c2cd5876a4f29be0aab2286b979a30dc5985fa5194aa4a7d

**Comment by betatim** [comment]
Could you try with a newer version of repo2docker? Since we released 0.10.0 several things have changed related to R support. On mybinder.org we run the very latest commit of repo2docker.

You can install the latest repo2docker with `pip install https://github.com/jupyter/repo2docker/archive/master.zip`

(We are due a new release soon ... :) )

**Comment by manics** [comment]
Closing due to lack of response
