### ISSUE TITLE
Returned a non-zero code: 137

### ISSUE THREAD

**Issue by tonyphoang** [jupyterhub/repo2docker#877]
```
+ conda env create -p /srv/conda/envs/notebook -f /tmp/environment.yml
Collecting package metadata (repodata.json): ...working... /tmp/install-miniconda.bash: line 51:   814 Killed                  conda env create -p ${NB_PYTHON_PREFIX} -f /tmp/environment.yml
Removing intermediate container ca72604e3311
The command '/bin/sh -c bash /tmp/install-miniconda.bash && rm /tmp/install-miniconda.bash /tmp/environment.yml' returned a non-zero code: 137
```
Got the following error when I tried to run
jupyter-repo2docker --user-id 1000 --user-name tony https://github.com/xxxxxxx

**Comment by betatim** [comment]
With out a link to your repository or one like it to reproduce the error we can't look into this. Please add one.

When reporting a possible bug please use the "Bug report" issue template and fill in as much of it as you can as it helps us help you.
