### ISSUE TITLE
Make binder/start script not need to be executable

### ISSUE THREAD

**Issue by danlester** [jupyterhub/repo2docker#883]
### Proposed change

If a start script is provided by the user, ensure that the [repo2odocker-entrypoint](https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/repo2docker-entrypoint) script makes it executable before running it. Or if not possible to change file permissions, run it through the appropriate interpreter explicitly (see alternative options below).

This is similar to Issue #241 for postBuild.

### Alternative options

Instead of changing file permissions, a more complex repo2docker-entrypoint script could parse the start script (probably safely assume it's not a binary file) and explicitly run it through the specified hash-bang interpreter (e.g. #!/bin/bash).

Or the build process could copy the start script to $CONDA_DIR and run it from there - but there could be issues if the script is expecting itself to be in the repo's folder structure, e.g. in the .binder folder.

### Who would use this feature?

Mostly this isn't a problem as the start script is [given the correct permissions](https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/base.py#L185) during the Docker build process.

But in some cases, file permissions do not really exist, e.g. if the folder is mounted from a host system. E.g. building from a 'local folder' repo source when the final container is designed to mount the repo as /home/jovyan.

This happens, for example, in ContainDS software running on Windows or Mac (actually from any repo source in this case).

### How much effort will adding it take?

Estimated at 1 day.

### Who can do this work?

I would be happy to do this work myself but would like confirmation that more experienced contributors are happy with the approach.

Pointers to a relevant wide range of sample repos would be helpful too (e.g. R since I am more experienced with Python).

**Comment by betatim** [comment]
Sounds like a good idea. I would avoid trying to parse scripts and extracting things to then try and locate the right interpreter, etc. Sounds easy and like something that will be super hard to get right for the last 20% of cases.

We already do `chmod +x` for `binder/start` but you mention filesystems without executable permission are a problem. I'm not sure I understand/know what the entrypoint script could do if `chmod +x` didn't work.

**Comment by danlester** [comment]
Yes, you are right my original post was a bit confused: if chmod didn't work the first time around during build, we can probably assume it won't work in the entrypoint script either (although I will check this in my case.)

As a fallback I'm not personally terrified of parsing the script for clues, or maybe just running it through bash regardless. The point is we are in a case where the hoped-for behavior has failed, so risking further failure in difficult cases isn't too bad.

I'll run some tests on all of this, but any other thoughts are very welcome!

**Comment by manics** [comment]
Would it simplify things to say if it's not executable it will be run using `bash`? This avoids trying to parse a script, but still gives everyone a way out since they can always write a bash script to wrap any executable if for some reason they can't change the permissions.

**Comment by betatim** [comment]
I like Simon's suggestion to default to bash.

The difficulty with parsing the script and figuring out what to do isn't getting it right for most of the scripts. The hard part/maintenance burden is in the last few percent of scripts that do weird stuff which is legal but unusual/rarely done, breaks the ad-hoc parser and leads to weird errors. (A recent example is our parsing of `requirements.txt` files, we thought "how hard can it be?" ;) ). Most of the future maintenance cost comes from ad-hoc parsers leading to erros where the stack trace points to the wrong place. So I think we can also reduce it by making any parser like a small child: easily confused and then shouting loud right then and there. Compared to silently being confused which leads to breakage further downstream at which point it has become super hard to figure out what actually broke.

**Comment by danlester** [comment]
I was thinking the same ultimately, but I think Simon's breakthrough was to say that it defaults to bash _by definition_ which avoids disappointment when (as Tim says) we set ourselves up for failure in trying to guess the real intention for the script.

I'll run some tests as I work towards a PR anyway. Thanks everyone for your input.

**Comment by danlester** [comment]
I have made a simple PR just to chmod u+x the start script for now. That solves the 'mounted local folder' problem, and I think it should be enough for my ContainDS Desktop software's issue too. I'll keep an eye on it, and consider the 'bash default' idea if needed. Thanks again for your help!

**Comment by manics** [comment]
Is this something we still want? Or does the passing of a year mean https://github.com/jupyterhub/repo2docker/pull/886 is a good enough fix? :smile:

**Comment by danlester** [comment]
@manics thanks for bringing this back up! As far as I know, the existing PR keeps us happy!

I'll close, and anyone feel free to open if this is something they are interested in (perhaps the 'default to bash in failure' part).
