### ISSUE TITLE
Add support for R 4.0

### ISSUE THREAD

**Issue by nuest** [jupyterhub/repo2docker#887]
### Proposed change

Add support for R 4.0 to the R version map at https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/r.py#L71

**Alternatives:**

- Installation via conda, but there the latest version is also `3.6`.
- Use [`holepunch`](https://github.com/karthik/holepunch) and the [`rocker/binder`](https://hub.docker.com/r/rocker/binder/tags) image, though no `4.0.0` tag there either yet.

### Alternative options

IMO: None.

### Who would use this feature?

People demonstrating latest R features, or relying on latest packages requiring R 4.0, or trying to match their own environment closely.

### How much effort will adding it take?

Not much, _if/when the version is available via the default Ubuntu sources.

### Who can do this work?

Anyone with experience in running repo2docker tests and some R experience for testing.

**Comment by betatim** [comment]
We should remove/cut down most of the version support in https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/r.py#L71 as it is broken. We built that on top of functionality which the creators of those r packages never intended :-/

My vote is to suggest using https://github.com/binder-examples/r-conda as the way to get different R versions installed. To get R 4.0 support someone needs to update the conda-forge package (which means repo2docker gets it "for free").

**Comment by scottyhq** [comment]
@betatim and @nuest - just noting that in order to install R4.0 from conda-forge with repo2docker I had to use the following environment.yml:
```
channels:
  - conda-forge
dependencies:
  - r-base>=4
  - r-irkernel>=1.1
```

Otherwise it appears repo2docker has an incompatible r-irkernel version pinned, as seen in the output from this build step:
`Step 42/62 : RUN conda install -p ${NB_PYTHON_PREFIX} r-base=4 r-irkernel=1.0.2 r-devtools && conda clean --all -f -y && conda list -p ${NB_PYTHON_PREFIX}`

**Comment by betatim** [comment]
Interesting. https://github.com/jupyter/repo2docker/pull/892 bumped the version of irkernel and I had thought that would fix it. Which version of repo2docker did this happen with?

**Comment by scottyhq** [comment]
Ah, thanks @betatim - i missed those recent changes since I was using the latest release locally (jupyter-repo2docker==0.11).

**Comment by betatim** [comment]
Following up my comment from May 2rd: https://stat.ethz.ch/pipermail/r-sig-debian/2019-November/003121.html is the message that made me think that we got lucky with using the different R versions from that PPA ever worked.
