### ISSUE TITLE
A simple question: where is the output of repo2docker

### ISSUE THREAD

**Issue by aborruso** [jupyterhub/repo2docker#905]
Hi,
I have build a complex Docker image using repo2docker.

I'm using it in debian, starting from a system folder.  But I have no idea on where is the repo2docker output and what's the right way to delete it.

Thank you

**Comment by manics** [comment]
Sorry for the delay in responding to this. We've got a bot that directs people to our [community forum](https://discourse.jupyter.org/) for support questions, but it looks like it failed to respond to you.
