### ISSUE TITLE
Integration with Jupyter enterprise gateway and jupyterhub

### ISSUE THREAD

**Issue by kartoch** [jupyterhub/repo2docker#916]
Hello,

I'm deploying a Kubernetes cluster with jupyterhub and jupyter enterprise gateway, and I was wondering how to integrate repo2docker to permit docker build on-demand. I don't see any issue / proposal on the subject, but it would be the perfect modular jupyter installation: isolation and customization of notebooks via container.

### Proposed change

- instead of starting the container with the select image, jupyter entreprise gateway checks if the repo2docker recognized configuration files are present (Dockerfile, etc.). 

- If no, it starts the default image

- If yes, it calls a docker build with repo2docker and kaniko in a dedicated pod. After the build is succesful, the image reference is given to jupyter entreprise gateway which can start the image.

### Alternative options

At the present time, choosing a specific notebook container image can be done using form during jupyterhub authentication. The cluster administrator has to build specific image based on user request and add its to the form choices.

### Who would use this feature?

Notebook user who wants customization of notebook environments.

### How much effort will adding it take?

I don't really know, I see these main 3 tasks:

- modify repo2docker to just build the image and not starting a container
- dedicate the build in a specific pod (using kaniko)
- pass the image name to jupyter enterprise gateway

### Who can do this work?

Devs from jupyter entreprise gateway and repo2docker.

**Comment by ctr26** [comment]
Is binderhub on kubernetes not sufficient for your needs?

**Comment by kartoch** [comment]
Thank you for your response. I discovered binderhub after submitting this issue, and forgot to close it.
