### ISSUE TITLE
JupyterLab 3.0 strategy

### ISSUE THREAD

**Issue by manics** [jupyterhub/repo2docker#935]
### Proposed change
Update to JupyterLab 3.0 when it's released. Switch default from notebook to the planned [lab classic notebook mode view](https://github.com/jupyterhub/jupyterhub/issues/2634#issuecomment-664641973).

### Alternative options
- Upgrade to JupyterLab 3.0 but keep the default jupyter-notebook view.

### Who would use this feature?
Hopefully everyone! This is a follow-on from https://github.com/jupyter/repo2docker/issues/724
Related issues:
- [JupyterLab as the Default? jupyterhub#2634](https://github.com/jupyterhub/jupyterhub/issues/2634)
- [JupyterLab - the default? zero-to-jupyterhub-k8s#776](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/776)

### How much effort will adding it take?
- Upgrading to JupyterLab 3.0 will require extensions to be updated, but assuming there are no major API changes this should be straightforward and just require bumping versions of dependencies.
- Switching the default interface will require investigation since the [URL needs to change to `/doc`](https://github.com/jupyterhub/jupyterhub/issues/2634#issuecomment-664641973).

### Who can do this work?
- Anyone can follow the [instructions for updating conda packages](https://repo2docker.readthedocs.io/en/latest/contributing/tasks.html#conda-dependencies).
- Changing the default requires knowledge of the repo2docker codebase

# Required changes (please edit and update as required)

- [ ] Update JupyterLab
- [ ] Update jupyter-offlinenotebook (pip installable for JupyterLab 3)
- [ ] [Switch from nbresuse to jupyter-resource-usage](https://github.com/jupyterhub/repo2docker/issues/935#issuecomment-747468748)
- [ ] Switch default URL from `/tree` to either `/doc` or `lab`

**Comment by SylvainCorlay** [comment]
Update to JupyterLab 3.0 will hopefully reduce a lot the build time for extensions and all, thanks to the webpack module federation.

**Comment by manics** [comment]
Yes, I'm looking forward to it 😄 . From a repo2docker point of view we need to wait until enough current lab extensions have been updated so we don't break too many repositories.

**Comment by jtpio** [comment]
There is now some documentation about updating extensions to be compatible with 3.x, as well as using the new extension distribution system (with pip and conda): 

https://jupyterlab.readthedocs.io/en/latest/developer/extension_migration_2_3.html

**Comment by jtpio** [comment]
Adding a new TODO item, now that [`jupyter-resource-usage`](https://github.com/jupyter-server/jupyter-resource-usage) has been published to PyPI:

- [ ] Switch from `nbresuse` to `jupyter-resource-usage`

The package includes a prebuilt extension for JupyterLab 3.0 that displays the memory usage as a status bar item. It was originally part of the JupyterLab code base but has now been moved to `jupyter-resource-usage` (see https://github.com/jupyterlab/jupyterlab/pull/9386 and https://github.com/jupyter-server/jupyter-resource-usage/pull/69 for more info).

**Comment by manics** [comment]
@jtpio Thanks for the note about `jupyter-resource-usage`, I've copied it to the main description

On a separate note, I've noticed the latest JupyterLab no longer runs on mybinder, going to `/lab` results in a 404:
https://mybinder.org/v2/gist/manics/922d4e88fefc6d38fccea8cd2097bc28/HEAD?urlpath=%2Flab

**Comment by jtpio** [comment]
> On a separate note, I've noticed the latest JupyterLab no longer runs on mybinder, going to /lab results in a 404:

It's probably related to jupyter server now requiring `tornado>=6.1`. It should normally be fixed with `jupyterlab==3.0.0rc14` (more info in https://github.com/jupyterlab/jupyterlab/pull/9453 and linked issues and PRs).
