### ISSUE TITLE
JupyterLab 3.0.0a10 /lab url doesn't work

### ISSUE THREAD

**Issue by manics** [jupyterhub/repo2docker#945]
# Bug description
Normally repo2docker defaults to launching Jupyter Notebook, but you can switch to JupyterLab by changing the URL path to `/lab`. This fails with JupyterLab 3.0.0a10 (the latest pre-release).
JupyterLab release schedule: https://github.com/jupyterlab/jupyterlab/issues/8038

#### Expected behaviour
Going to `/lab` should take you to the JupyterLab interface

#### Actual behaviour
You get the Jupyter 404 page:
```
404 : Not Found

You are requesting a page that does not exist!
```

### How to reproduce
Click on https://mybinder.org/v2/gist/manics/922d4e88fefc6d38fccea8cd2097bc28/master?urlpath=lab
Or run
`repo2docker https://gist.github.com/manics/922d4e88fefc6d38fccea8cd2097bc28` and go to `/url`

Although the default will remain JupyterLab 2.0 for the immediate future I think we should ensure 3.0 works for anyone who wants to use it (https://github.com/jupyterhub/repo2docker/issues/935)

**Comment by manics** [comment]
@blink1073 Do you know if this is something we should fix in the repo2docker launcher, or is it related to the lab integration with some other component?

**Comment by blink1073** [comment]
This is related to https://github.com/jupyterhub/jupyterhub/pull/3128.   The recommended way to use JuptyerLab 3.0 with JupyterHub is to use `c.Spawner.cmd=["jupyter-labhub"]`

**Comment by blink1073** [comment]
We fixed the ability to launch `jupyterlab` as a classic notebook extension in https://github.com/jupyterlab/jupyterlab/pull/8956 (pending another beta release).  We will eventually remove this capability once everyone has migrated to using `jupyter_server`.

**Comment by manics** [comment]
Thanks! I can confirm JupyterLab 3.0.0b3 works with repo2docker 👍 

I've opened a separate issue for updating repo2docker to work with jupyter_server https://github.com/jupyterhub/repo2docker/issues/956

**Comment by blink1073** [comment]
Great, thanks @manics!
