### ISSUE TITLE
Switch to using jupyter_server to launch singleuser servers

### ISSUE THREAD

**Issue by manics** [jupyterhub/repo2docker#956]
### Proposed change
This is a follow-up from https://github.com/jupyterhub/repo2docker/issues/945

`jupyter_server` is a new way of launching singleuser apps such as Jupyter notebook and JupyterLab. Pre-releases of JupyterLab 3 used this new class but they [failed to launch with repo2docker](https://github.com/jupyterhub/repo2docker/issues/945). The ability to run JupyterLab using the old method was restored, and JupyterLab 3.0.0b3 now works with repo2docker.

Repo2docker should be updated to work with the new method.

### Alternative options
If we do nothing JupyterLab 4 will fail to launch.

### Who would use this feature?
Existing users. Also anyone who want to launch an alternative singleuser server on repo2docker.

### How much effort will adding it take?
I don't know, perhaps someone who understands what's changed could outline what needs to be done?

### Who can do this work?
See previous

**Comment by yuvipanda** [comment]
Do we know where we are at with this, @manics?

**Comment by manics** [comment]
I don't think we've changed anything yet. However this should happen automatically when jupyterhub-singleuser is upgraded from 1.5.0 to 3.0.0 (since 2.0.0 switched the default to jupyter-server/JupyterLab).

I've started work on the upgrade but there are some complications:
https://github.com/jupyterhub/repo2docker/pull/1196#issuecomment-1286028421
Any help/suggestions welcome!
