### ISSUE TITLE
possible to disable labextensions?

### ISSUE THREAD

**Issue by minrk** [jupyterhub/repo2docker#964]
I've been doing some repo2docker development recently, which means that the base conda environment is getting installed a lot. The big frustration in this process has ben that roughly half (or more) of my build time is spent in `jupyter labextension install jupyter-offlinenotebook`. That's more than two minutes per build (see #919 for an example breakdown of timings). I recognize that this is something most real users won't see since this layer will often be cached, but it's been pretty devastating for my development cycle.

Is there any way that we can cache labextensions separately, or make them optional? This is a useful extension for Binder, but it's really not beneficial and extremely costly for local repo2docker.

**Comment by manics** [comment]
Longer term options:
- Get rid of the build step with jupyterlab modules: https://github.com/jupyterlab/jupyterlab-module-federation
- Allow the Jupyter UI environment to be managed separately from the execution environment, so for instance we could have a way to define which extensions are installed or not: https://github.com/jupyterhub/repo2docker/issues/868

Short term fix: maybe a docker environment variable that activates a "development" mode and skips the build step?

**Comment by ccordoba12** [comment]
I came here to also mention this. I just noticed this new step when rebuilding our [Binder images](https://github.com/spyder-ide/binder-environments) for Spyder (I don't remember it a week ago).

Binder is a very useful service and we're using it more and more in our organization. So please don't skew things to favor JuoyterLab because that affects other projects that have no relation to it.

**Comment by manics** [comment]
@ccordoba12 this isn't new, it's been in repo2docker since February: https://github.com/jupyterhub/repo2docker/pull/845, and JupyterLab has been included for even longer.

**Comment by ccordoba12** [comment]
Sorry, I just noticed it now (perhaps because I paid more to the logs this time). In any case, I think my second comment above is still valuable.

**Comment by manics** [comment]
https://github.com/jupyterhub/repo2docker/issues/868 is probably the best solution if it can be implemented, since in theory you could completely disable jupyterlab and notebook.

**Comment by manics** [comment]
Is there anything we want to do here? The original motivation (reduce build time) is no longer an issue due to the new JupyterLab 3 extension packaging system.

**Comment by yuvipanda** [comment]
Yeah, it's just a pip install now.
