### ISSUE TITLE
binder failed to launch: RAM error when compiling rstan

### ISSUE THREAD

**Issue by yanxianl** [jupyterhub/repo2docker#968]
### Bug description
Hi, I used the [holepunch](https://karthik.github.io/holepunch/) package to make my repo binder-ready. The binder has been working without problems until recently it failed to build. The build failed when compiling rstan package. The error message is very similar to what is described [here](https://github.com/stan-dev/rstan/issues/713) and it seems to be a RAM issue.

### How to reproduce

1. Go to my repo: https://github.com/yanxianl/Li_AqFl2-Microbiota_ASM_2020
2. Click on ![Launch Binder](http://mybinder.org/badge_logo.svg) (takes hours to build).
3. See error

**Comment by manics** [comment]
In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Hope you understand 😀.
