### ISSUE TITLE
environment.yml works, environment.yaml doesn't

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/repo2docker#970]
### Bug description

Hey 👋 Not sure if this is a bug or an intentional feature so opened an issue for discussion.

When building an image using conda, repo2docker accepts `environment.yml` files but does not pick up `environment.yaml` files. Is there a reason for this that I'm missing?

#### Expected behaviour

Both the `.yml` and `.yaml` file extensions would be valid and repo2docker would successfully build both envs with conda.

#### Actual behaviour

Only the `.yml` file is recognised. Building with `.yaml` succeeds but none of the requested packages are installed.

### How to reproduce

I created two repos to test this on mybinder.org.

**.yml extension:**
Repo: https://github.com/sgibson91/test_repo_yml
Binder link: https://mybinder.org/v2/gh/sgibson91/test_repo_yml/main

**.yaml extension:**
Repo: https://github.com/sgibson91/test_repo_yaml
Binder link: https://mybinder.org/v2/gh/sgibson91/test_repo_yaml/main

Both repos contain environment files that should install numpy, pandas and matplotlib. By clicking the binder links, opening a new notebooks and attempting to import any (or all) of these packages is **successful** in the **.yml** repo and **fails** in the **.yaml** repo.

### Your personal set up

Currently testing on mybinder.org

**Comment by manics** [comment]
If someone managed to include both yml and yaml files what would be the expected behaviour?

**Comment by sgibson91** [comment]
We could add an order of preference like with the directories? Prefer yml over yaml?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/choose-packaging-environment-in-binder/6399/4

**Comment by manics** [comment]
An alternative could be to have some sort of pre-build check/lint on BinderHub (perhaps implemented as an optional r2d argument) where it could look for problems we've seen before e.g. incorrectly named files, binder and .binder directories, etc, and popup an "are you sure this is correct" dialog?

**Comment by sgibson91** [comment]
Maybe? I'll be honest, JavaScript scares me 😅 I guess the missing piece of information for me is, is there a historical reason why r2d doesn't accept .yaml? That's why I said I wasn't sure if it's a bug or intentional.

**Comment by betatim** [comment]
I would not add support for this. I think `environment.yaml` is pretty rare and it seems people have "agreed" that `environment.yml` is the name everyone should use. It is also the one mentioned in documentation like https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

**Comment by sgibson91** [comment]
OK, so how about @manics idea of a pre-build check for commonly seen mistakes such as this? (I can reframe the original issue comment if needed)

**Comment by betatim** [comment]
I wouldn't prioritise it because I don't think it is a common problem :-/

**Comment by HTenkanen** [comment]
@betatim : Just found myself debugging this for an hour because `.yaml` file wasn't detected.. 

Nowadays I believe `.yaml` is becoming more widely used for writing environment files (although `.yml` can still be seen due to historical reasons of Windows users). Using `.yaml` is in fact the [recommendation by the YAML itself](https://yaml.org/faq.html). Hence, would it be possible to add support for detecting also environment file with `.yaml` extension? Also e.g. GitHub Actions support both naming conventions.
