### ISSUE TITLE
Detect default branch instead of assuming master (at least for GitHub repos)

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/repo2docker#971]
### Proposed change

GitHub (at least) now supports setting your default branch to something other than `master`, the recommended option being `main`. https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/
This can be confusing for new users of mybinder.org, e.g. https://discourse.jupyter.org/t/cant-solve-could-not-resolve-ref-for-gh-fredericfoulonlycee-math-spe-python-master/6301
We should change repo2docker's behaviour to search for/fetch the default branch name of the git repository, rather than assuming/hard code it to being `master`.

I don't know if r2d assumes everything is a git repository or if this is something we'll specifically have to build into the GitHub repo handling section.

### Alternative options

We continue to wait until this is more common before carrying out this work. Perhaps adding an information box to the front page of mybinder.org so folks are aware.

### Who would use this feature?

Everybody who has created a new GitHub repository since 1st October 2020 or have manually renamed their default branches.

### How much effort will adding it take?

I imagine there's a git command we can run to fetch the default branch name and then parse that into our standard branch handling code for non-`master` branches.

### Who can do this work?

Useful skills:

- Knowledge of the r2d codebase: where things are being parsed to, etc
- Some git fu to detect the default branch name

**Comment by manics** [comment]
Related though not identical issue: https://github.com/jupyterhub/binderhub/issues/1145

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/choose-packaging-environment-in-binder/6399/4
