### ISSUE TITLE
Repo2docker release including mamba

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterhub/repo2docker#980]
I don't think that there has been a release since the move to mamba. Releasing repo2docker woul also enable the benefits of mamba in other clients that don't use the master branch, like tljh-repo2docker...

**Comment by jtpio** [comment]
Just like the Docker images, maybe the `jupyter-repo2docker` Python package could be published automatically?

That would mean having a new job on CI to automate releases to PyPI, using the same tag as the Docker image for the package version.

**Comment by manics** [comment]
@jtpio I like the idea! We encourage people to install repo2docker from master, which is equivalent to tagging every release.
The Docker tags aren't compliant with [pep-440](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers). Do you happen to know whether pypi would accept them as a release version anyway?

**Comment by jtpio** [comment]
> The Docker tags aren't compliant with [pep-440](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers)

Ah right. Not sure but it might be possible to check the behavior with a test package.

Otherwise using part of the tag / version could also work, and would help compare a Python package with a Docker image. For example: 

![image](https://user-images.githubusercontent.com/591645/98690223-00fe3800-236d-11eb-8cf8-455ca6a1ef60.png)

**Comment by SylvainCorlay** [comment]
> We encourage people to install repo2docker from master, which is equivalent to tagging every release.

Why encouraging people to use repo2docker master instead of tagging releases?

Having a release made available on PyPI and conda etc (with constraints on dependencies) would probably be very beneficial for the repo2docker adoption, and its packaging for various package managers.

**Comment by manics** [comment]
@SylvainCorlay that's what I meant 😀. Since we already recommend installing from master there should be no barrier to making a release after every PR merged. The usual arguments like code being unstable don't apply.

**Comment by SylvainCorlay** [comment]
Gotcha :) One argument may be semver / backward compatibility.

**Comment by manics** [comment]
Just a heads-up for anyone interested, automatic releases is on the agenda for tomorrow's JupyterHub team meeting https://hackmd.io/YpwhVwbSSpCG19I0JNpqjQ?view

**Comment by SylvainCorlay** [comment]
Any update on a potential release?

**Comment by SylvainCorlay** [comment]
Hey @manics @minrk, a convenience tag would be greatly appreciated, independently of the team figuring out the calendar-based automatic releases.

**Comment by manics** [comment]
Sorry for not updating this, a semi-manual calendar release was made last month https://github.com/jupyterhub/repo2docker/releases/tag/2021.01.0
