### ISSUE TITLE
Bump pipenv version

### ISSUE THREAD

**Issue by rubendibattista** [jupyterhub/repo2docker#986]
### Bug description
Currently `repo2docker` [is using `pipenv==2018.11.25`](https://github.com/jupyterhub/repo2docker/blob/master/repo2docker/buildpacks/pipfile/__init__.py#L91). This fails with a project I'm working [on Binder](https://mybinder.org/v2/gl/rubendibattista%2Fjosiepy/a9fa8d7466d28a7eb0bb87f5b663b6711fa9c279/?filepath=examples%2F002_Advection.ipynb). 
On my machine and on CI the `pipenv install` works as expected so I guess it's related to `pipenv` version.

#### Expected behaviour
`repo2docker` should use the latest  `pipenv`  version

#### Actual behaviour
`repo2docker` uses an old `pipenv` version

### How to reproduce
https://mybinder.org/v2/gl/rubendibattista%2Fjosiepy/a9fa8d7466d28a7eb0bb87f5b663b6711fa9c279?filepath=examples%2F002_Advection.ipynb

**Comment by manics** [comment]
Are there any breaking changes in pipenv that could potentially break compatibility with existing repositories? If not I think it should be OK to update it. Is this something you're interested in contributing?

**Comment by rubendibattista** [comment]
> Are there any breaking changes in pipenv that could potentially break compatibility with existing repositories? If not I think it should be OK to update it. Is this something you're interested in contributing?

Well, not that I'm aware of. I will send a PR then. 😉

**Comment by rubendibattista** [comment]
Ok, i tried to bump `pipenv`, but the issues is the same. 

I actually found what the issue is related to: https://github.com/jupyterhub/repo2docker/issues/827

So, since in `repo2docker` image you already have `jupyter` installed, using `pipenv --system` on a `Pipfile.lock` that has `jupyter` in it causes the build to fail. 

```
 ---> Running in 5a1724f95030
Installing dependencies from Pipfile.lock (347577)...
An error occurred while installing terminado==0.9.1; python_version >= '3.6' --hash=sha256:c55f025beb06c2e2669f7ba5a04f47bb3304c30c05842d4981d8f0fc9ab3b4e3 --hash=sha256:3da72a155b807b01c9e8a5babd214e052a0a45a975751da3521a1c3381ce6d76! Will try again.
Installing initially failed dependencies...
[InstallError]:   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/pipenv/cli/command.py", line 233, in install
[InstallError]:       retcode = do_install(
[InstallError]:   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/pipenv/core.py", line 2052, in do_install
[InstallError]:       do_init(
[InstallError]:   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/pipenv/core.py", line 1304, in do_init
[InstallError]:       do_install_dependencies(
[InstallError]:   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/pipenv/core.py", line 899, in do_install_dependencies
[InstallError]:       batch_install(
[InstallError]:   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/pipenv/core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/pipenv/core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: Collecting terminado==0.9.1
[pipenv.exceptions.InstallError]:   Using cached terminado-0.9.1-py3-none-any.whl (13 kB)
[pipenv.exceptions.InstallError]: Installing collected packages: terminado
[pipenv.exceptions.InstallError]:   Attempting uninstall: terminado
[pipenv.exceptions.InstallError]:     Found existing installation: terminado 0.8.3
[pipenv.exceptions.InstallError]: ERROR: Cannot uninstall 'terminado'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
ERROR: Couldn't install package: terminado
 Package installation failed...
```

Any idea on how to solve this?

**Comment by rubendibattista** [comment]
So this is basically a duplicate of #827
